### ISSUE TITLE
Possibility to add occupancy sensor data to API?

### ISSUE THREAD

**Issue by Gtwizzy** [lukas-clarke/pyEight#2]
I know that a lot of people only use temp set but it would be great to see if the occupancy sensor info could be pulled as this may be more reliable under the new API than the old one.

Could this potentially be added?

**Comment by lukas-clarke** [comment]
I'm pretty busy this week, but I can likely take a look at this next week.

**Comment by Gtwizzy** [comment]
Thank you 🙏🙏 I really want to pull this back into Home assistant but just don't have the technical knowledge to get as far down the rabbit hole as you have with this so any code you can write is GREATLY appreciated by myself and I am SURE a bunch of other people

**Comment by lukas-clarke** [comment]
Created a Home Assistant integration at https://github.com/lukas-clarke/eight_sleep

Unfortunately, the new Eight Sleep API still doesn't have a way to reliably pull presence and/or sleep state so it works the same as the old integration.
